phases:
- phase: Phase_0
  displayName: Ensure Formatting, Lint

  condition: succeeded()
  queue:
    name: Hosted macOS

  steps:
    - task: GoTool@0
      displayName: 'Use Go 1.11'
      inputs:
        version: 1.11
    - script: |
        set -ev
        mkdir -p ~/go
        export GOPATH=~/go
        export PATH=${PATH}:${GOPATH}/bin
        echo "${GOPATH}"
        go get -u golang.org/x/lint/golint
      displayName: 'Install golint'
    - script: |
        set -ev
        export PATH=${PATH}:${GOPATH}/bin
        make lint
      env:
        GOPATH: ~/go
      displayName: 'Run Linters'

- phase: Phase_1
  displayName: Execute Tests on Linux
  dependsOn: Phase_0

  condition: succeeded()
  queue:
    name: Hosted Ubuntu 1604

  steps:
  - task: GoTool@0
    displayName: 'Use Go 1.11'
    inputs:
      version: 1.11
  - script: |
      go mod download
    displayName: 'Download Dependencies'
  - script: |
      set -ev
      make test
    displayName: 'Execute Tests'

- phase: Phase_2
  displayName: Execute Tests on Windows
  dependsOn: Phase_0

  condition: succeeded()
  queue:
      name: Hosted

  steps:
  - task: GoTool@0
    displayName: 'Use Go 1.11'
    inputs:
      version: 1.11
  - script: |
      go mod download
    displayName: 'Download Dependencies'
  - task: Go@0
    inputs:
      command: test
      arguments: ./...
    displayName: 'Execute Tests'

- phase: Phase_3
  displayName: Execute Tests on Mac
  dependsOn: Phase_0

  condition: succeeded()
  queue:
    name: Hosted macOS

  steps:
  - task: GoTool@0
    displayName: 'Use Go 1.11'
    inputs:
      version: 1.11
  - script: |
      go mod download
    displayName: 'Download Dependencies'
  - script: |
      set -ev
      make test
    displayName: 'Execute Tests'