phases:
- phase: Phase_0
  displayName: Ensure Formatting, Lint

  condition: succeeded()
  queue:
    name: Hosted macOS

  steps:
    - task: GoTool@0
      displayName: 'Use Go 1.12'
      inputs:
        version: 1.12
    - script: |
        set -ev
        mkdir -p ~/go
        export GOPATH=~/go
        export PATH=${PATH}:${GOPATH}/bin
        echo "${GOPATH}"
        go get -u golang.org/x/lint/golint
      displayName: 'Install golint'
    - script: |
        set -ev
        export PATH=${PATH}:${GOPATH}/bin
        make lint
      env:
        GOPATH: /Users/vsts/go
      displayName: 'Run Linters'

- phase: Phase_1
  displayName: Linux
  dependsOn: Phase_0

  condition: succeeded()
  queue:
    name: Hosted Ubuntu 1604

  steps:
  - task: GoTool@0
    displayName: 'Use Go 1.12'
    inputs:
      version: 1.12
  - script: |
      go mod download
    displayName: 'Download Dependencies'
  - script: |
      set -ev
      make test
    displayName: 'Execute Tests'
  - script: |
      make linux
      cp bin/linux/baronial $BUILD_ARTIFACTSTAGINGDIRECTORY/
    displayName: 'Build Executable'
  - task: PublishBuildArtifacts@1
    inputs:
      artifactName: 'linux'
    displayName: 'Publish Executable'

- phase: Phase_2
  displayName: Windows
  dependsOn: Phase_0

  condition: succeeded()
  queue:
      name: Hosted

  steps:
  - task: GoTool@0
    displayName: 'Use Go 1.12'
    inputs:
      version: 1.12
  - script: |
      go mod download
    displayName: 'Download Dependencies'
  - task: Go@0
    inputs:
      command: test
      arguments: ./...
    displayName: 'Execute Tests'
  - task: Go@0
    inputs:
      command: build
      arguments: -o $(Build.ArtifactStagingDirectory)/baronial.exe -ldflags "-X github.com/marstr/baronial/cmd.revision=$(Build.SourceVersion)"
    displayName: 'Build Executable'
  - task: PublishBuildArtifacts@1
    inputs:
      artifactName: 'windows'
    displayName: 'Publish Executable'

- phase: Phase_3
  displayName: MacOSX
  dependsOn: Phase_0

  condition: succeeded()
  queue:
    name: Hosted macOS

  steps:
  - task: GoTool@0
    displayName: 'Use Go 1.12'
    inputs:
      version: 1.12
  - script: |
      go mod download
    displayName: 'Download Dependencies'
  - script: |
      set -ev
      make test
    displayName: 'Execute Tests'
  - script: |
      make darwin
      cp bin/darwin/baronial $BUILD_ARTIFACTSTAGINGDIRECTORY/
    displayName: 'Build Executable'
  - task: PublishBuildArtifacts@1
    inputs:
      artifactName: 'darwin'
    displayName: 'Publish Executable'