ARG alpine_version=3.9

FROM golang:alpine${alpine_version} AS builder

RUN apk add --no-cache --update alpine-sdk gcc make git perl

WORKDIR /usr/local/src/baronial

COPY go.* ./

RUN go mod download

COPY . .

RUN make install

CMD /bin/bash

FROM alpine:${alpine_version} AS execution

COPY --from=builder /go/bin/baronial /usr/local/bin

CMD /bin/sh
