ARG tag=buster

FROM debian:${tag} AS builder
RUN apt update; apt install -y golang perl make git

WORKDIR /usr/local/src/baronial

COPY go.* ./

RUN go mod download

COPY . .

RUN make bin/linux/baronial

CMD /bin/bash

FROM debian:${tag} AS execution

COPY --from=builder /usr/local/src/baronial/bin/linux/baronial /usr/local/bin/

CMD /bin/bash
