ARG tag=10

FROM debian:${tag} AS builder
RUN apt update; apt install -y golang perl make git debhelper

WORKDIR /usr/local/src/baronial

COPY go.* ./

RUN go mod download

COPY . .

RUN make version.txt revision.txt
RUN mv packaging/debian ./

CMD /bin/bash

FROM debian:${tag} AS execution

COPY --from=builder /usr/local/src/baronial/bin/linux/baronial /usr/local/bin/

CMD /bin/bash
