ARG alpine_version=3.11

FROM alpine:${alpine_version} AS builder

RUN apk add --no-cache --update alpine-sdk gcc make git perl go

WORKDIR /usr/local/src/baronial

COPY go.* ./

RUN go mod download

COPY . .

RUN make install

CMD /bin/bash

FROM alpine:${alpine_version} AS execution

COPY --from=builder /root/go/bin/baronial /usr/local/bin

CMD /bin/sh
