name: Build

on:
  push:
    branches: [ main ]
  release:
    types:
      - created

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build
        run: make linux
      - name: Test
        run: make test
      - uses: actions/upload-artifact@v2
        with:
          name: Baronial Linux
          path: bin/linux/baronial

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build
        run: .\make.bat
      - name: Test
        run: go test -v ./...
      - uses: actions/upload-artifact@v2
        with:
          name: Baronial Windows
          path: bin/windows/baronial.exe

  build-darwin:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build
        run: make darwin
      - name: Test
        run: make test
      - uses: actions/upload-artifact@v2
        with:
          name: Baronial Darwin
          path: bin/darwin/baronial

  build-fedora33:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
          with:
            fetch-depth: 0
        - name: Build
          run: |
            make bin/linux/baronial.fc33.src.rpm bin/linux/baronial.fc33.x86_64.rpm
        - uses: actions/upload-artifact@v2
          with:
            name: baronial.fc33.src.rpm
            path: bin/linux/baronial.fc33.src.rpm
        - uses: actions/upload-artifact@v2
          with:
            name: baronial.fc33.x86_64.rpm
            path: bin/linux/baronial.fc33.x86_64.rpm
  build-fedora34:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build
        run: |
          make bin/linux/baronial.fc34.src.rpm bin/linux/baronial.fc34.x86_64.rpm
      - uses: actions/upload-artifact@v2
        with:
          name: baronial.fc34.src.rpm
          path: bin/linux/baronial.fc34.src.rpm
      - uses: actions/upload-artifact@v2
        with:
          name: baronial.fc34.x86_64.rpm
          path: bin/linux/baronial.fc34.x86_64.rpm
  build-fedora35:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build
        run: |
          make bin/linux/baronial.fc35.src.rpm bin/linux/baronial.fc35.x86_64.rpm
      - uses: actions/upload-artifact@v2
        with:
          name: baronial.fc35.src.rpm
          path: bin/linux/baronial.fc35.src.rpm
      - uses: actions/upload-artifact@v2
        with:
          name: baronial.fc35.x86_64.rpm
          path: bin/linux/baronial.fc35.x86_64.rpm
